name: secret scanning


on: 
  push:
    branches:
      - main
      - dev
      - test
      - stage
  pull_request:
    branches:
      - main
      - dev
      - test
      - stage

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret Scanner
        uses: github/codeql-action/init@v2
        with:
          languages: 'all'
      - name: Perform secret scanning
        uses: github/codeql-action/analyze@v2
        with:
          category: 'secret-scanning'
      - name: Upload Secret Scanning Results
        uses: actions/upload-artifact@v3
        with:
          name: secret-scanning-results
          path: .
          if-no-files-found: warn

       
